"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hetarth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link
          rel="shortcut icon"
          href="https://fontawesome.com/icons/code?f=classic&s=solid"
          type="image/x-icon"
        />
      </head>
      <body
        suppressHydrationWarning={true}
        className={inter.className}
        // style={{ backgroundColor: "#1B2430", color: "white" }}
      >
        <ThemeProvider enableSystem={true} attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
