"use client";
import "./globals.css";
import { Inter } from "next/font/google";

const theme = localStorage["theme"];
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Hetarth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`scroll-smooth ${theme}`}>
      <head>
        <link
          rel="shortcut icon"
          href="https://fontawesome.com/icons/code?f=classic&s=solid"
          type="image/x-icon"
        />
      </head>
      <body suppressHydrationWarning={true} className={inter.className}>
        {children}
      </body>
    </html>
  );
}
