import Head from "next/head";
import { Inter } from "@next/font/google";
import Footer from "./footer";
import Navbar from "./navbar";
import Home from "./home";
import Projects from "./projects";
import Resume from "./resume";
import Blog from "./blog";
import Contact from "./contact";

const inter = Inter({ subsets: ["latin"] });

export default function Root() {
  return (
    <>
      <Head>
        <title>Hetarth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head>
      <Navbar />
      <Home />
      <Projects />
      <Resume />
      <Blog />
      <Contact />
      <Footer />
    </>
  );
}
