import Head from "next/head";
import { Inter } from "@next/font/google";
import Footer from "./footer";
import Navbar from "./navbar";
import Home from "./home";
import Work from "./work";

export default function Root() {
  return (
    <>
      <Head>
        <title>Hetarth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head>
      <Navbar />
      <Home />
      <Work />
      <Footer />
    </>
  );
}
