import Navbar from "./navbar";
import About from "./about";
import Work from "./work";
import Projects from "./projects";
import Connect from "./connect";
import Head from "next/head";
export default function Home() {
  return (
    <div className="w-fit">
      <Head>
        <title>Hetarth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <About />
      <Work />
      <Projects />
      <Connect />
    </div>
  );
}
